version: '3.7'

services:

  node:
    build:
      context: ./services/node
      dockerfile: Dockerfile-dev
    restart: always
    volumes:
      - './services/node:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-tier
    depends_on:
      - redis
    
  redis:
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redis:/bitnami/redis/data
    networks:
      - app-tier
    container_name: redis_dos

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 80:80
    networks:
      - app-tier
    depends_on:
      - node

volumes:
  data:
    driver: "local"

networks: 
  app-tier:
    driver: "bridge"